#ifndef CONFIG_H
#define CONFIG_H

#define APP_NAME "blocks"
#define APP_WIDTH 1024
#define APP_HEIGHT 764
#define APP_VALIDATION 1
#define APP_ICON BLOCK_ROSE

#define ATLAS_WIDTH 256.0
#define ATLAS_HEIGHT 256.0
#define ATLAS_FACE_WIDTH 16.0
#define ATLAS_FACE_HEIGHT 16.0
#define ATLAS_X_FACES 16.0
#define ATLAS_Y_FACES 16.0
#define ATLAS_LEVELS 7

#define PLAYER_SPEED 0.015f
#define PLAYER_SPRINT_SPEED 0.03f
#define PLAYER_SENSITIVITY 0.1f
#define PLAYER_Y 60

#define SHADOW_SIZE 4096
#define SHADOW_Y 30.0f
#define SHADOW_PITCH (-PI / 4.0f)
#define SHADOW_YAW (PI / 8.0f)

#define CHUNK_X 30
#define CHUNK_Y 30
#define CHUNK_Z 30
#define GROUP_CHUNKS 7
#define GROUP_X (CHUNK_X)
#define GROUP_Y (CHUNK_Y * GROUP_CHUNKS)
#define GROUP_Z (CHUNK_Z)
#define WORLD_X 20
#define WORLD_Y (GROUP_CHUNKS)
#define WORLD_Z 20
#define WORLD_GROUPS (WORLD_X * WORLD_Z)
#define WORLD_CHUNKS (WORLD_Y * WORLD_GROUPS)
#define WORLD_JOBS 3000
#define WORLD_WORKERS 4

#define DATABASE_JOBS 100
#define DATABASE_PATH "blocks.sqlite3"
#define DATABASE_COOLDOWN 1000
#define DATABASE_PLAYER 0

#define VOXEL_X_BITS 5
#define VOXEL_Y_BITS 5
#define VOXEL_Z_BITS 5
#define VOXEL_U_BITS 4
#define VOXEL_V_BITS 4
#define VOXEL_DIRECTION_BITS 3
#define VOXEL_SHADOW_BITS 1
#define VOXEL_X_OFFSET (0)
#define VOXEL_Y_OFFSET (VOXEL_X_OFFSET + VOXEL_X_BITS)
#define VOXEL_Z_OFFSET (VOXEL_Y_OFFSET + VOXEL_Y_BITS)
#define VOXEL_U_OFFSET (VOXEL_Z_OFFSET + VOXEL_Z_BITS)
#define VOXEL_V_OFFSET (VOXEL_U_OFFSET + VOXEL_U_BITS)
#define VOXEL_DIRECTION_OFFSET (VOXEL_V_OFFSET + VOXEL_V_BITS)
#define VOXEL_SHADOW_OFFSET (VOXEL_DIRECTION_OFFSET + VOXEL_DIRECTION_BITS)
#define VOXEL_X_MASK ((1 << VOXEL_X_BITS) - 1)
#define VOXEL_Y_MASK ((1 << VOXEL_Y_BITS) - 1)
#define VOXEL_Z_MASK ((1 << VOXEL_Z_BITS) - 1)
#define VOXEL_U_MASK ((1 << VOXEL_U_BITS) - 1)
#define VOXEL_V_MASK ((1 << VOXEL_V_BITS) - 1)
#define VOXEL_DIRECTION_MASK ((1 << VOXEL_DIRECTION_BITS) - 1)
#define VOXEL_SHADOW_MASK ((1 << VOXEL_SHADOW_BITS) - 1)

#define BUTTON_FORWARD SDL_SCANCODE_W
#define BUTTON_BACKWARD SDL_SCANCODE_S
#define BUTTON_LEFT SDL_SCANCODE_A
#define BUTTON_RIGHT SDL_SCANCODE_D
#define BUTTON_UP SDL_SCANCODE_E
#define BUTTON_DOWN SDL_SCANCODE_Q
#define BUTTON_SPRINT SDL_SCANCODE_LCTRL
#define BUTTON_BLOCK SDL_SCANCODE_B
#define BUTTON_PAUSE SDL_SCANCODE_ESCAPE
#define BUTTON_FULLSCREEN SDL_SCANCODE_F11
#define BUTTON_PLACE SDL_BUTTON_RMASK
#define BUTTON_BREAK SDL_BUTTON_LMASK

#define DRAW_NORMALS 0
#define DRAW_SSAO 0
#define DRAW_LIGHTS 0
#define DRAW_COLORS 0
#define DRAW_SHADOWED 0

#endif
